//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA
    {
        public long ID_BODEGA { get; set; }
        public long ID_EDIFICIO { get; set; }
        public double DIMENSION_BODEGA { get; set; }
        public string NUMERO_BODEGA { get; set; }
        public Nullable<long> DEP_BODEGA { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
    }
}
