//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOLETA()
        {
            this.BOLETA_GASTO = new HashSet<BOLETA_GASTO>();
            this.ESTACIONAMIENTO_VISITA1 = new HashSet<ESTACIONAMIENTO_VISITA>();
            this.RESERVA_CENTRO = new HashSet<RESERVA_CENTRO>();
        }
    
        public long ID_BOLETA { get; set; }
        public Nullable<long> ID_ESTACIONAMIENTO { get; set; }
        public Nullable<long> ID_PERSONA { get; set; }
        public Nullable<long> DEP { get; set; }
        public long COSTO_BOLETA { get; set; }
        public string CODIGO_TRANSACCION { get; set; }
        public string FECHA_REGISTRO_BOLETA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETA_GASTO> BOLETA_GASTO { get; set; }
        public virtual ESTACIONAMIENTO_VISITA ESTACIONAMIENTO_VISITA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTACIONAMIENTO_VISITA> ESTACIONAMIENTO_VISITA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA_CENTRO> RESERVA_CENTRO { get; set; }
    }
}
