//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA_GASTO
    {
        public long ID_BOLETA { get; set; }
        public long ID_GASTOS { get; set; }
        public string MES { get; set; }
        public string ANO { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual GASTOS_COMUNES GASTOS_COMUNES { get; set; }
    }
}
