//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CENTRO()
        {
            this.HORARIO_CENTRO = new HashSet<HORARIO_CENTRO>();
            this.RESERVA_CENTRO = new HashSet<RESERVA_CENTRO>();
        }
    
        public long ID_CENTRO { get; set; }
        public long ID_TIPO_CENTRO { get; set; }
        public long ID_EDIFICIO { get; set; }
        public string NOMBRE_CENTRO { get; set; }
        public int COSTO { get; set; }
        public string FECHA_REGISTRO_CENTRO { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual TIPO_CENTRO TIPO_CENTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO_CENTRO> HORARIO_CENTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA_CENTRO> RESERVA_CENTRO { get; set; }
    }
}
