//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDOMINIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDOMINIO()
        {
            this.CONSERJE = new HashSet<CONSERJE>();
            this.DIRECCION1 = new HashSet<DIRECCION>();
            this.EDIFICIO = new HashSet<EDIFICIO>();
        }
    
        public long ID_CONDOMINIO { get; set; }
        public Nullable<long> ID_DIRECCION { get; set; }
        public Nullable<long> ID_PERSONA { get; set; }
        public string NOMBRE_CONDOMINIO { get; set; }
        public int PRECIO_EST { get; set; }
        public string FECHA_REGISTRO_CONDOMINIO { get; set; }
    
        public virtual DIRECCION DIRECCION { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSERJE> CONSERJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCION> DIRECCION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDIFICIO> EDIFICIO { get; set; }
    }
}
