//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSERJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSERJE()
        {
            this.TURNO = new HashSet<TURNO>();
        }
    
        public long ID_CONSERJE { get; set; }
        public long ID_PERSONA { get; set; }
        public Nullable<long> ID_CONDOMINIO { get; set; }
        public string FECHA_REGISTRO_CONSERJE { get; set; }
    
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNO> TURNO { get; set; }
    }
}
