//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_ILUMINACION_DEPARTAMENTO
    {
        public long ID_CILUMINACION_D { get; set; }
        public long ID_LUZ_D { get; set; }
        public string HORA_INICIO_D { get; set; }
        public string HORA_TERMINO_D { get; set; }
        public bool ESTADO_LUZ_CD { get; set; }
        public bool ESTADO_CONTROL_D { get; set; }
    
        public virtual LUZ_DEPARTAMENTO LUZ_DEPARTAMENTO { get; set; }
    }
}
