//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_ILUMINACION_EDIFICIO
    {
        public long ID_CILUMINACION_E { get; set; }
        public long ID_LUZ_E { get; set; }
        public string HORA_INICIO_E { get; set; }
        public string HORA_TERMINO_E { get; set; }
        public bool ESTADO_LUZ_CE { get; set; }
        public bool ESTADO_CONTROL_E { get; set; }
    
        public virtual LUZ_EDIFICIO LUZ_EDIFICIO { get; set; }
    }
}
