//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENTO()
        {
            this.LUZ_DEPARTAMENTO1 = new HashSet<LUZ_DEPARTAMENTO>();
            this.MULTA = new HashSet<MULTA>();
            this.RESERVA_CENTRO = new HashSet<RESERVA_CENTRO>();
        }
    
        public long ID_DEPARTAMENTO { get; set; }
        public Nullable<long> ID_PERSONA { get; set; }
        public long ID_EDIFICIO { get; set; }
        public Nullable<long> ID_LUZ_D { get; set; }
        public string NUMERO_DEP { get; set; }
        public string FECHA_REGISTRO_DEP { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual LUZ_DEPARTAMENTO LUZ_DEPARTAMENTO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUZ_DEPARTAMENTO> LUZ_DEPARTAMENTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MULTA> MULTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA_CENTRO> RESERVA_CENTRO { get; set; }
    }
}
