//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDIFICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDIFICIO()
        {
            this.CENTRO = new HashSet<CENTRO>();
            this.DEPARTAMENTO = new HashSet<DEPARTAMENTO>();
            this.GASTOS_COMUNES1 = new HashSet<GASTOS_COMUNES>();
            this.LUZ_EDIFICIO = new HashSet<LUZ_EDIFICIO>();
        }
    
        public long ID_EDIFICIO { get; set; }
        public Nullable<long> ID_GASTOS { get; set; }
        public long ID_CONDOMINIO { get; set; }
        public string NOMBRE_EDIFICIO { get; set; }
        public int CANTIDAD_PISO { get; set; }
        public int CANTIDAD_DEPARTAMENTO { get; set; }
        public string FECHA_REGISTRO_EDIFICIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CENTRO> CENTRO { get; set; }
        public virtual CONDOMINIO CONDOMINIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual GASTOS_COMUNES GASTOS_COMUNES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GASTOS_COMUNES> GASTOS_COMUNES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUZ_EDIFICIO> LUZ_EDIFICIO { get; set; }
    }
}
