//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTACIONAMIENTO_VISITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTACIONAMIENTO_VISITA()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public long ID_ESTACIONAMIENTO { get; set; }
        public Nullable<long> ID_BOLETA { get; set; }
        public string NUM_DEP { get; set; }
        public long EDIFICIO { get; set; }
        public string PATENTE { get; set; }
        public string HORA_ENTRADA { get; set; }
        public string HORA_SALIDA { get; set; }
        public bool ESTADO_EST { get; set; }
        public int TOTAL_EST { get; set; }
        public string FECHA_ESTACIONAMIENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual BOLETA BOLETA1 { get; set; }
    }
}
