//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUZ_EDIFICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUZ_EDIFICIO()
        {
            this.CONTROL_ILUMINACION_EDIFICIO = new HashSet<CONTROL_ILUMINACION_EDIFICIO>();
        }
    
        public long ID_LUZ_E { get; set; }
        public Nullable<long> ID_EDIFICIO { get; set; }
        public string CODIGO_LUZ_E { get; set; }
        public bool ESTADO_LUZ_E { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_ILUMINACION_EDIFICIO> CONTROL_ILUMINACION_EDIFICIO { get; set; }
        public virtual EDIFICIO EDIFICIO { get; set; }
    }
}
