//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUZ_DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUZ_DEPARTAMENTO()
        {
            this.CONTROL_ILUMINACION_DEPARTAMENTO = new HashSet<CONTROL_ILUMINACION_DEPARTAMENTO>();
            this.DEPARTAMENTO = new HashSet<DEPARTAMENTO>();
        }
    
        public long ID_LUZ_D { get; set; }
        public Nullable<long> ID_DEPARTAMENTO { get; set; }
        public string CODIGO_LUZ_D { get; set; }
        public bool ESTADO_LUZ_D { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_ILUMINACION_DEPARTAMENTO> CONTROL_ILUMINACION_DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO1 { get; set; }
    }
}
