//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTA
    {
        public long ID_MULTA { get; set; }
        public long ID_DEPARTAMENTO { get; set; }
        public Nullable<long> ID_BOLETA { get; set; }
        public string MOTIVO { get; set; }
        public long COSTO_MULTA { get; set; }
        public bool ESTADO_MULTA { get; set; }
        public string FECHA_REGISTRO_MULTA { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
