//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_CENTRO
    {
        public long ID_RESERVA_CENTRO { get; set; }
        public long ID_DEPARTAMENTO { get; set; }
        public long ID_CENTRO { get; set; }
        public Nullable<long> ID_BOLETA { get; set; }
        public long COD_HORARIO { get; set; }
        public string FECHA_RESERVA_C { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
